Decoding made robust against invalid polyline strings
vahancho/polylineencoder pull request #2
Opened 2019-11-05 12:10 UTC by AlexisRiksman

The polyline decoder function is now robust against invalid polyline strings
that would result in missing or invalid coordinates. On invalid strings the
decoder returns an empty list of coordinates.

Signed-off-by: Alexis Riksman <alexis.riksman@tomtom.com>

2019-11-05 13:54 UTC, vahancho requested changes

2019-11-05 13:54 UTC, vahancho commented on src/polylineencoder.cpp
> -    assert(i < coords.size());
Please don't remove this precondition check.

2019-11-05 13:54 UTC, vahancho commented on src/polylineencoder.cpp
>          auto lat = decode(coords, i);
This might fail. It doesn't make sense to continue afterwards. I suggest to check the return value right away and exit the function.

2019-11-05 13:54 UTC, vahancho commented on src/polylineencoder.cpp
>          auto lon = decode(coords, i);
This might fail. It doesn't make sense to continue afterwards. I suggest to check the return value right away  and exit the function.

2019-11-05 13:54 UTC, vahancho commented on test/main.cpp
> +    return test(__func__, encoder, "??");
__func__ isn't defined and the build fails. Please make the code to compile.

2019-11-05 16:34 UTC, AlexisRiksman-TomTom commented on test/main.cpp
> +    return test(__func__, encoder, "??");
Changed this to __FUNCTION__
No idea why __func__ does not compile, it is supposed to be part of C++11.

2019-11-05 16:35 UTC, AlexisRiksman-TomTom commented on src/polylineencoder.cpp
>          auto lon = decode(coords, i);
Reworked this code, please review again.

2019-11-05 16:41 UTC, AlexisRiksman commented
@vahancho : Is it possible to skip the coverage for main.cpp, as these clutter up the coverage statistics?

2019-11-06 08:36 UTC, vahancho commented
> @vahancho : Is it possible to skip the coverage for main.cpp, as these clutter up the coverage statistics?

You are right - we don't need to measure coverage of unit tests. I think it's possible to ignore it. I will take care of it.

2019-11-06 08:44 UTC, vahancho approved these changes

2019-11-06 08:46 UTC, vahancho commented
Thank you for contributing to the project!

2019-11-06 08:48 UTC, merged

2019-11-06 15:39 UTC, AlexisRiksman commented
> Thank you for contributing to the project!

My pleasure.
Your work saved me a lot of time, so I consider it obvious to contribute where possible.

Good luck with your projects, and thanks for publishing them !